apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  labels:
    app: wordpress
type: Opaque
data:
  db-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  db-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
