apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
