apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress.fullname" . }}-nfs-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: {{ .Values.wordpress.nfs.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.wordpress.nfs.server }}
    path: {{ .Values.wordpress.nfs.path }}
  mountOptions:
{{- range .Values.wordpress.nfs.mountOptions }}
    - {{ . }}
{{- end }}
